### PR TITLE
Update docs for automatic/strategy attributes and reflection/term rewriting

### PR DESCRIPTION
**Pull request by krame505**
TODO: this is currently missing a link for the reflection COLA paper.  Otherwise this is ready to merge.

### CODE REVIEW

**Comment by krame505** [comment]
@ericvanwyk I'd like to merge this today, in case people somehow end up on our website after watching my talk.

**Review by ericvanwyk — APPROVED** [review]

**Comment by ericvanwyk** [comment]
Sorry, @krame505  - I missed this.  Please merge when you are ready.  Don't hesitate to email me if I don't see something like this.

**Comment by krame505** [comment]
Thanks.  I am still waiting on a link for the COLA paper that we can link here on the reflection/term rewriting page - are you able post this on your publications page?

**Comment by ericvanwyk** [comment]
did it now

https://www-users.cs.umn.edu/~evw/pubs/kramer21cola/index.html

**Pull request merged**
